// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.normandy.migrationsApplied", 12);
user_pref("app.update.lastUpdateTime.region-update-timer", 0);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 0);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.cache.disk.enable", false);
user_pref("browser.cache.memory.enable", false);
user_pref("browser.migration.version", 175);
user_pref("browser.proton.toolbar.version", 3);
user_pref("browser.region.update.updated", 1786318422);
user_pref("browser.search.region", "FR");
user_pref("browser.uiCustomization.state", "{\"placements\":{\"widget-overflow-fixed-list\":[],\"unified-extensions-area\":[]},\"seen\":[\"reset-pbm-toolbar-button\"],\"dirtyAreaCache\":[],\"currentVersion\":24,\"newElementCount\":0}");
user_pref("datareporting.dau.cachedUsageProfileGroupID", "75ce2b88-d169-4ced-8fda-5bd7d176f930");
user_pref("datareporting.dau.cachedUsageProfileID", "d5a01cba-98e9-4893-937e-b126457d4332");
user_pref("devtools.console.stdout.content", true);
user_pref("distribution.archlinux.bookmarksProcessed", true);
user_pref("distribution.iniFile.exists.appversion", "153.0.3");
user_pref("distribution.iniFile.exists.value", true);
user_pref("dom.forms.autocomplete.formautofill", true);
user_pref("extensions.activeThemeID", "default-theme@mozilla.org");
user_pref("extensions.blocklist.pingCountVersion", 0);
user_pref("extensions.databaseSchema", 37);
user_pref("extensions.getAddons.databaseSchema", 6);
user_pref("extensions.lastAppBuildId", "20260804131232");
user_pref("extensions.lastAppVersion", "153.0.3");
user_pref("extensions.lastPlatformVersion", "153.0.3");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.pictureinpicture.enable_picture_in_picture_overrides", true);
user_pref("extensions.signatureCheckpoint", 1);
user_pref("extensions.webextensions.uuids", "{\"formautofill@mozilla.org\":\"ee0d5772-83bf-4fc4-90ec-934a2a3cde10\",\"ipp-activator@mozilla.com\":\"d365a3e7-020f-4d3a-9f41-6835dd1fd559\",\"pictureinpicture@mozilla.org\":\"e2bb23ec-9514-42a1-9831-2fd9c325bac4\",\"addons-search-detection@mozilla.com\":\"dfe0fd77-4ee4-44c0-8c5b-61bb17e31119\",\"webcompat@mozilla.org\":\"9a310967-e580-48bf-b3e8-4eafebbc122d\",\"newtab@mozilla.org\":\"e2743bc9-4cf8-4f62-873a-a8d88c7c6637\",\"default-theme@mozilla.org\":\"b0e1b9f4-f466-44b8-a45b-ae7943b19532\"}");
user_pref("media.autoplay.default", 0);
user_pref("media.gmp.storage.version.observed", 1);
user_pref("media.navigator.permission.disabled", true);
user_pref("media.navigator.streams.fake", true);
user_pref("media.navigator.streams.fake.height", 960);
user_pref("media.navigator.streams.fake.width", 1280);
user_pref("network.cookie.CHIPS.lastMigrateDatabase", 2);
user_pref("network.cookie.validation.lastEpoch", 1);
user_pref("nimbus.profileId", "cfabaf96-2029-4b1e-b0f2-5a7699577ec0");
user_pref("pdfjs.enabledCache.state", true);
user_pref("privacy.bounceTrackingProtection.hasMigratedUserActivationData", true);
user_pref("privacy.trackingprotection.allow_list.hasMigratedCategoryPrefs", true);
user_pref("services.sync.engine.addresses.available", true);
user_pref("toolkit.profiles.newProfileSubmitted", true);
user_pref("toolkit.startup.last_success", 1786318418);
user_pref("toolkit.telemetry.cachedClientID", "b7981ad4-f530-483e-a5e6-95cf5d023487");
user_pref("toolkit.telemetry.cachedProfileGroupID", "874490d3-9755-4794-a611-39ccbe677c4f");
user_pref("toolkit.telemetry.previousBuildID", "20260804131232");
